### ISSUE TITLE
cli es6 error

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction-cli#2]
`reaction` is giving error:

```
/usr/local/lib/node_modules/reaction-cli/dist/utils/logger.js:31
exports.default = Object.assign(_chalk2.default, loggers);
                         ^
TypeError: undefined is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/reaction-cli/dist/utils/logger.js:31:26)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/reaction-cli/dist/utils/fs.js:18:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

node version: v0.12.2

**Comment by jshimko** [comment]
This was because of an older version of Node that didn't support Object.assign().  This has been polyfilled (and fixed) with Lodash.
https://github.com/reactioncommerce/reaction-cli/commit/3fbcf4fc817eef94585186d53bd4a8e0fd60457e
