### ISSUE TITLE
Upgrading to RC-CLI v0.21.2 errors

### ISSUE THREAD

**Issue by mikeumus** [reactioncommerce/reaction-cli#49]
After running `npm i -g reaction-cli`, `rc run` or `rc reset` gives following error:

```
> $ reaction reset                                                [±custom-cart_rc1.5.8-0 ✓]
/usr/lib/node_modules/reaction-cli/node_modules/yargs/yargs.js:1079
      else throw err
           ^

SyntaxError: Unexpected token < in JSON at position 1833
    at Object.parse (native)
    at exports.default (/usr/lib/node_modules/reaction-cli/dist/utils/check_app.js:25:16)
    at exports.default (/usr/lib/node_modules/reaction-cli/dist/utils/check_deps.js:22:29)
    at Object.builder (/usr/lib/node_modules/reaction-cli/dist/main.js:112:24)
    at Object.self.runCommand (/usr/lib/node_modules/reaction-cli/node_modules/yargs/lib/command.js:195:35)
    at Object.Yargs.self._parseArgs (/usr/lib/node_modules/reaction-cli/node_modules/yargs/yargs.js:990:30)
    at Object.get [as argv] (/usr/lib/node_modules/reaction-cli/node_modules/yargs/yargs.js:927:19)
    at Object.<anonymous> (/usr/lib/node_modules/reaction-cli/dist/main.js:163:196)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```

_ _ _

`rc --version`

Node: 6.11.5
NPM: 3.10.10
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.21.2

_ _ _

Downgrading to RC-CLI v0.21.1, the error persists. :)

**Comment by mikeumus** [comment]
False alarm.
